### ISSUE TITLE
Missing package or...?

### ISSUE THREAD

**Issue by Quacky2200** [cronvel/freedesktop-notifications#1]
I'm trying to use your package in my electron application but I get an error due to an 'undefined symbol' error in abstract-socket, however when I view your dependencies, abstract-socket is not present.I have tried to install abstract-socket into the node_modules directory but it still doesn't work, is there a specific version you used so I can track down the error?
![screenshot from 2017-01-08 11-16-02](https://cloud.githubusercontent.com/assets/4623599/21749312/4164b6ba-d594-11e6-8373-cc3bf0a10c05.png)
I get this error with or without the abstract-socket module

**Comment by cronvel** [comment]
This lib only relies on *dbus-native*, however, as you can see in the error message, *dbus-native* needs *abstract-socket*. 

It looks like the native modules was not compiled for *Electron*, did you install it with *npm* or with *Electron* specific tools?
Anyway, if you have done it right, your problem may come from *dbus-native* or *abstract-socket*, so you may try to ask their respective author about *Electron*'s compatibility.

*Electron* doesn't have its own notification API?

**Comment by Quacky2200** [comment]
Electron does have their own implementation for notifications but it uses libnotify and notifications cannot be cleared if I need to replace them. Previously I used your library that allowed me to 'spam' notifications on track changes (i.e. user keeps clicking on different tracks) otherwise the notifications would keep appearing in a slow queue. I used a separate binary of node and used an interpreter between the processes to send and receive messages but I cannot keep doing this because it prevents me from packaging my application into an AppImage and it's quite irritating to depend on a separate process to process notifications. I am starting to get version differences between npm builds which makes it hard to keep track of (besides the point of a node library being native in Electron). I think there's some kind of difference in libnode.so that Electron uses and node that prevents an abstract-socket from being created.

I did try to [convert your library](https://gist.github.com/Quacky2200/5b3d98fad17e8f394b710ee775ec1dbe#file-test-conversion-js-L32-L90) to use a different [dbus](https://github.com/Shouqun/node-dbus) library that doesn't use an abstract socket and I can get the notifications to show purely from Electron, but I cannot dismiss/spam them like previously. I only changed the highlighted since I'm not exactly an expert with D-Bus libraries.

**Comment by cronvel** [comment]
Ok I understand. I can't remember how to integrate native module in *Electron* (done it only once). 

It seems [that it is the official way of doing it](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) now. Do you have followed those steps? Did the native modules compiled without any error or warning?

**Comment by Quacky2200** [comment]
I've been trying to do as you suggested but now the dbus (not dbus-native) module won't get built as it cannot find the ldbus-1(libdbus-1-dev?) library. I have built the library before so I'm not sure why it's happening now. I need to move to 64bit Ubuntu so I may try again after the move.

**Comment by Quacky2200** [comment]
I think you'll be glad to hear that I got it working. I moved to 64 bit to ease development. I realised the small mistakes when setting up my dev environment. The library error was because I set Electron to rebuild 64 bit in a 32 bit environment, needing to change a bit of code to make sure everything was satisfactory and of course a fresh set of eyes. 

Thanks for the help :)

**Comment by cronvel** [comment]
Great!
