### ISSUE TITLE
Persistence isn't working

### ISSUE THREAD

**Issue by jcuenod** [cronvel/freedesktop-notifications#2]
Well, more correctly, I can't figure out how to get notifications to persist.

I tried with `persistence: true` and I tried `-1` but I've also tried various settings with `timeout` and `priority`. I'm on Gnome-shell 3.24.2 - I've been delving into gnome docs and their own apis and even considering just making my own dbus calls but then I figured there was probably a simple solution to this...

**Comment by cronvel** [comment]
@jcuenod The problem is not the lib, and not D-Bus. This lib deals directly with D-Bus.
The D-Bus *freedesktop notification* protocol is really simple, but the notification server does what it want with your notification.

However, there is no *persistence* option in that protocol, instead set the *urgency* option to 2 or *critical*, **that the only way I know to force Gnome to not close a notification automatically.**

**Comment by jcuenod** [comment]
It's definitely possible to persist notifications because I have some that survive until I manually close them. Are they communicating with a different server or something?

**Comment by cronvel** [comment]
**Have you read my comment?**
Set the urgency to 'critical':
```javascript
var notif = notifications.createNotification( {
    summary: 'Hello world!' ,
    body: 'Hello world!' ,
    urgency: 'critical'
} ) ;

notif.push() ;
```

**Comment by jcuenod** [comment]
Okay, thanks. I don't really want to force the user to interact with the notification immediately which is what the urgency setting does.

In addition to `urgency`, on https://developer.gnome.org/notification-spec/#protocol I see the following:
> "persistence"	The server supports persistence of notifications. Notifications will be retained until they are acknowledged or removed by the user or recalled by the sender. The presence of this capability allows clients to depend on the server to ensure a notification is seen and eliminate the need for the client to display a reminding function (such as a status icon) of its own.

As well as:
> expire_timeout	INT32	
> The timeout time in milliseconds since the display of the notification at which the notification should automatically close.
> If -1, the notification's expiration time is dependent on the notification server's settings, and may vary for the type of notification. If 0, never expire.

But don't worry, maybe gnome's notification server is not implemented according to spec or something...

**Comment by cronvel** [comment]
As you can see in the doc you quoted, *persistence* is not a notification option, but merely a server capability. 
There isn't any *persistence* attribute.

Persistence *should* be handled via the *timeout* option, but Gnome gladly ignore it. Gnome just doesn't support its own documentation.

Frankly, that standard is just BS, and notification server implementation are even worst.
