### ISSUE TITLE
Scripts won't terminate automatically

### ISSUE THREAD

**Issue by zawata** [cronvel/freedesktop-notifications#3]
I haven't seen this issue reported by anyone anywhere else so i think it may be my system. 

I'm running ubuntu budgie which itself already has issues with the freedesktop notification spec(ie. urgencies are ignored on notifications).

Basically the script won't terminate after completion, it appears to soft lock somewhere in the  v8 engine(even the debugging engine can't single step. It wont re-enter any js code, not even the tick functions) 

The issue seems to be tied to dbus connections being that they don't close themselves automatically(or at least I would assume they are supposed to), and therefore starting a connection will lock the node runtime until said connection is closed. This can be accomplished by calling `sessionBus.connection.end();` I could be able to do this from the outside the library except the sessionBus variable inst exported, making it much more difficult to access.

As I type this out I'm thinking I may have to make an issue with dbus-native instead. I just wanted to post it for opinions.

**Comment by cronvel** [comment]
@zawata I can't remember if it was already the case back to the day I created this module. I terminate explicitly on most node project, so I can't tell.
We probably have to deal with it.

**Comment by zawata** [comment]
I would terminate explicitly except I was intending to create a daemon that launched when I connected to wifi.  I can't explicitly close a daemon and if i had to manually kill it every time I might as well just run it as a script in the first place. 

If i just have to deal with it, then I'll probably either end up modifying the package to give me access to the sessionBus variable from my script, cutting out some parts and re-appropriating them, or just moving the whole thing over to python. I just really liked the simplicity of this package.

I guess if there's nothing to fix you can close this.

**Comment by cronvel** [comment]
@zawata I don't get it. If it's a daemon, it is not supposed to stop, except explicitly (e.g. `systemctl stop my-daemon`, or at system shutdown).

**Comment by zawata** [comment]
You're right. I meant daemon interface script not a daemon itself. More specifically a script executed on ifup.

**Comment by cronvel** [comment]
After adding a method to explicitly close the dbus connection, the bug is still there, so it's probably on the *dbus-native* module end.

**Comment by hash-bang** [comment]
Actually, I had a dig around with why the process wasn't terminating and after a bit of hair-pulling found that if you disable these lines:

```
// Default to 30 seconds low and normal priority or 10 minutes for critical priority
timeout = self.antiLeakTimeout || ( self.hints.urgency === 2 ? 600000 : 30000 ) ;

self.timer = setTimeout( self.close.bind( self , 'antiLeak' ) , timeout ) ;
```

Everything works as expected.

I suspect the problem is that the timers aren't being cleaned up correctly when the notification is closed (even though `cleanup()` _seems_ to look like it does)

**Comment by cronvel** [comment]
@hash-bang Ah I get it... In fact everything is working.
Simply, Gnome does not send any event when the notification time out.
That's it: if the user close the pop up the close event is sent, but if Gnome suppress the notification because the user is AFK for example, no close event is sent.

So you have to wait for 30 seconds before the clean up... Those notification servers are really terrible... :/

**Comment by cronvel** [comment]
@hash-bang @zawata Ok, I think it's fixed now.
I added a 'fireAndForget' option to the notification.
When used, and when there isn't another non- *fire and forget* notification hanging, the D-Bus connection is closed afterwards, and no timer will hang.

BTW, this mode is not compatible with *actions* and no event will be emitted on the notification (like the 'close' event), hence the fire and **forget** name.

**Comment by hash-bang** [comment]
Ah fantastic. Much appreciated.

**Comment by zawata** [comment]
I don't have the time or the original project I was working on to check if this is still an issue but reading the thread it seems like it was fixed so I'll close it.
